server:
  port: 8080
  servlet:
    context-path: /spring

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update  # hoặc: none, create, create-drop
    show-sql: true
# biến để mã hóa token
jwt:
  signerKey: "j5OpX/HPUqCo0s7kqwOvE6evdmJdfEczYef41YaetDODrWGncpEvOWdHmSJNXZAN"


